version: '3'

services:
   # Prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  # Grafana
  grafana:
    image: grafana/grafana:5.2.4
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana-storage:/var/lib/grafana

  # Docker stats exporter
  docker_stats_exporter:
    build: ./docker_stats_exporter
    ports:
      - "8088:8080" # Port 8088'i uygun bir şekilde ayarlayabilirsiniz
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage:
